[tool.poetry]
name = "da-boilerplate"
version = "0.1.0"
description = "Dynamic aperture boilerplate for LHC (including HL-LHC) simulations"
authors = ["Colas Droin <colas.noe.droin@cern.ch>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
xmask = {path = "external_dependencies/xmask", develop = true}
tree-maker = {git = "https://github.com/xsuite/tree_maker.git"}
xsuite = "*"
fastparquet = "*"
cupy-cuda11x = "*"
psutil = "*"
cpymad = "*"
nafflib = "*"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
